export const env: { [s: string]: string | null } = {
  npm_package_version: '${RELEASE_VERSION}',
  DEFAULT_MODEL : '${DEFAULT_MODEL}',
  NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT : '${NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT}',
  NEXT_PUBLIC_DEFAULT_TEMPERATURE : '${NEXT_PUBLIC_DEFAULT_TEMPERATURE}',
  GPT_API_HOST : '${GPT_API_HOST}',
  GPT_API_TYPE : '${GPT_API_TYPE}',
  GPT_API_VERSION : '${GPT_API_VERSION}',
  GPT_ORGANIZATION : '${GPT_ORGANIZATION}',
  AZURE_DEPLOYMENT_ID : '${AZURE_DEPLOYMENT_ID}',
  GOOGLE_API_KEY : '$GOOGLE_API_KEY',
  GOOGLE_CSE_ID : '$GOOGLE_CSE_ID',
};
